apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: shso9201/openalpr-worker:latest
        env:
        - name: MINIO_HOST
          value: "minio-proj.minio-ns.svc.cluster.local:9000"  # The MinIO service hostname in Kubernetes
        - name: MINIO_ACCESS_KEY
          value: "rootuser"   # Replace with your MinIO access key
        - name: MINIO_SECRET_KEY
          value: "rootpass123"   # Replace with your MinIO secret key
        - name: REDIS_HOST
          value: "redis"  # This should match the name of the Redis service
        - name: POSTGRES_HOST
          value: "postgres"  # This should match the name of the PostgreSQL service
        - name: POSTGRES_USER
          value: "postgres"  # Replace with your PostgreSQL username
        - name: POSTGRES_PASSWORD
          value: "yourpassword"  # Replace with your PostgreSQL password
        - name: POSTGRES_DB
          value: "yourdatabase"  # Replace with your PostgreSQL database name

